version: "3.7"

services:
  jupyter:
    image: jupyter/pyspark-notebook:latest
    ports:
      - 4040:4040 # spark 
      - 8888:8888 # jupyter
      - 10000:10000 # hive
    volumes:
      - .:/home/jovyan/work
    working_dir: /home/jovyan/work
    command: jupyter lab